### PR TITLE
New javascript with reworked /map and /transform pages

### LINKED ISSUE #97: Improved /map application
The application at http://epsg.io/5514/map should be rewritten into OpenLayers and further improved.

Inspiration from http://twcc.fr/en/ is welcome.

We should have it in two instances, one at http://epsg.io/map (a general one - allowing selection of the coordinate system of choice)

And another to show known coordinates in advance, such as http://epsg.io/5514/map or http://epsg.io/5514-5239/map (with transformation selected).

It should contain features like:
- Permalink for location in hash
- Formatting of the numbers a la twcc - #5 
- Selection of the coordinate system
- Responsive design (mobile optimised) done with @daliborjanak

### PR DESCRIPTION
**Pull request by petrsloup**
- major javascript cleaning (update to plovr 4.1.1, improved file structure, https://github.com/klokantech/javascript integration, ...)
- improved /map (ol3, reprojection beta, permalinks, dynamic srs changing, ...)
- new /transform page (with permalinks and dynamic linking to /map)
- responsive styling
- upgrade db to v8.8.1 (so the #102 can probably be closed, right?)

Closes #97 and #100.

### CODE REVIEW

**Comment by petrsloup** [comment]
@daliborjanak I think this can be merged when you are finished with the last changes.

**Comment by daliborjanak** [comment]
@petrsloup coud be merged now

**Comment by klokan** [comment]
Merged. Autodeployed. CDN reset. Everything seems to run.

Thank you everybody!

**Comment by klokan** [comment]
Andybody willing to write a related blog post draft?

**Comment by klokan** [comment]
@petrsloup precession rounding, esp. on lat/lon coordinates is insufficient.
If you zoom-in and move the map the numbers are not changing at all!

For latlon we have got similar complain from people using Gr4 in MapTiler. See:
http://maptiler.uservoice.com/forums/10188-maptiler-wish-list/suggestions/11329788-assign-location-visually-georeferencer-more-prec

**Comment by petrsloup** [comment]
@klokan I increased the precision to 6 decimal places (https://github.com/klokantech/epsg.io/commit/48b05f21b6b2c6bfa7c3ea2a702509701eb980cb; please purge cache). This should be roughly 11cm precision for lat/lon, which is enough (less than 1px on any map source we have).

**Pull request merged**
